# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2025-12-01 23:01
from __future__ import unicode_literals

import dau_issue.expressions
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("course_id", models.IntegerField(db_index=True)),
                ("kind", models.TextField(blank=True, default="")),
                ("performed_at", models.DateTimeField(db_index=True)),
                (
                    "properties",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict
                    ),
                ),
            ],
            options={
                "db_table": "dau_issue_event_event",
            },
        ),
        migrations.CreateModel(
            name="EventDauRollup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True, unique=True)),
                ("users", models.PositiveIntegerField()),
                ("returned", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "dau_issue_event_dau_rollup",
            },
        ),
        migrations.CreateModel(
            name="UserActivityRollup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(db_index=True)),
                ("user_id", models.IntegerField(db_index=True)),
            ],
            options={
                "db_table": "dau_issue_user_activity_rollup",
            },
        ),
        migrations.AlterUniqueTogether(
            name="useractivityrollup",
            unique_together=set([("day", "user_id")]),
        ),
        migrations.AddIndex(
            model_name="event",
            index=dau_issue.expressions.CustomIndex(
                expression="date(performed_at AT TIME ZONE 'UTC')",
                name="idx_event_performed_at_date",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["user_id", "performed_at"],
                name="dau_issue_e_user_id_9c8b99_idx",
            ),
        ),
    ]
